export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const FETCH_STUDENT_LIST = "FETCH_STUDENT_LIST";
export const FETCH_STUDENT_DETAIL = "FETCH_STUDENT_DETAIL";
export const FOLLOW_STUDENT = "FOLLOW_STUDENT";
export const UNFOLLOW_STUDENT = "UNFOLLOW_STUDENT";
export const FETCH_CATEGORY_LIST = "FETCH_CATEGORY_LIST";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const SUBMIT_ANSWER = "SUBMIT_ANSWER";
export const FETCH_STUDENT_LESSONS = "FETCH_STUDENT_LESSONS";
export const FETCH_STUDENT_LESSON = "FETCH_STUDENT_LESSON";
export const FETCH_STUDENT_LESSON_RESULT = "FETCH_STUDENT_LESSON_RESULT";
export const FETCH_STUDENT_ACTIVITYLOG = "FETCH_STUDENT_ACTIVITYLOG";

//Admin Functionality
export const ADMIN_CATEGORY_LIST = "ADMIN_CATEGORY_LIST";
export const ADMIN_CATEGORY_DETAIL = "ADMIN_CATEGORY_DETAIL";
export const ADMIN_UPDATE_CATEGORY = "ADMIN_UPDATE_CATEGORY";
export const ADMIN_DELETE_CATEGORY = "ADMIN_DELETE_CATEGORY";
export const ADMIN_ADD_CATEGORY = "ADMIN_ADD_CATEGORY";
export const ADMIN_ADD_QUESTION = "ADMIN_ADD_QUESTION";
export const ADMIN_QUESTION_LIST = "ADMIN_QUESTION_LIST";
export const ADMIN_QUESTION_RETRIEVE = "ADMIN_QUESTION_RETRIEVE";
export const ADMIN_QUESTION_UPDATE = "ADMIN_QUESTION_UPDATE";
export const ADMIN_QUESTION_DELETE = "ADMIN_QUESTION_DELETE";
export const ADMIN_USER_LIST = "ADMIN_USER_LIST";
