# Generated by Django 3.2.8 on 2021-10-16 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfollowinformation',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentfollowinformation',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
