# Generated by Django 3.2.8 on 2021-10-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_auto_20211016_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfollowinformation',
            name='following',
        ),
        migrations.AddField(
            model_name='studentfollowinformation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
