# Generated by Django 3.2.8 on 2021-10-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0003_auto_20211017_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfollowinformation',
            old_name='is_active',
            new_name='is_following',
        ),
    ]
