# Generated by Django 3.2.8 on 2021-10-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
    ]
