# Generated by Django 3.2.8 on 2021-10-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0006_auto_20211026_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
