# Generated by Django 3.2.8 on 2021-10-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0007_remove_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
