# Generated by Django 3.2.8 on 2021-11-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0009_alter_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
