# Generated by Django 3.2.8 on 2021-10-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0010_studentquestionanswered'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestionanswered',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_category_answer', to='learning_app.category'),
            preserve_default=False,
        ),
    ]
