# Generated by Django 3.2.8 on 2021-11-04 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_app', '0012_remove_studentactivitylog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfollowinformation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
