# Generated by Django 3.2.8 on 2021-10-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_alter_student_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
